### ISSUE TITLE
Setup Project (DB Included)

### ISSUE THREAD

**Issue by davidrabko** [daverbk/evolve#1]
1. Create db schema
2. Create backed project base + models (liquibase for migrations)
3. Create sql scripts for jpa / hibernate
4. Create frontend solution

**Comment by daverbk** [comment]
Believe it's done, [check it out](https://github.com/daverbk/evolve)

**Comment by Elovard** [comment]
Hey @daverbk ! Looks great but let's add some enhancements here:

1. Let's reduce boilerplate code by adding Lombok to the project. We can use @Entity, @Builder, @Getter, @Setter, @NoArgsConstructor and @AllArgsConstructor annotations.
![image](https://github.com/daverbk/evolve/assets/61758606/8804a465-dd94-42ad-87cf-3d9b0ca6cecb)

2. I guess we don't need a separate entity for Role. Let's simply create a Enum like this
![image](https://github.com/daverbk/evolve/assets/61758606/60b70899-65bc-4c2d-bdf4-4b79e3b55d4f)
![image](https://github.com/daverbk/evolve/assets/61758606/708bc459-5123-4a61-bf2a-e2ec6427cbc7)

3. I guess it'll be better to simply use Repositories and Services, not DAOs and DaoImpls. Like this
![image](https://github.com/daverbk/evolve/assets/61758606/3642f57c-d291-4066-8156-762dd75d1ea9)
And a method in a Service:
![image](https://github.com/daverbk/evolve/assets/61758606/69448174-0868-4959-863d-2ee5a989eecb)

4. We have to add JWT tokens but we can skip this part for now and do it in a separate issue 

I recommend you to check out this article which can be useful for current issue https://habr.com/ru/articles/784508/
It's a bit of advanced level, but anyway we will have to implement something like this in the project

**Comment by daverbk** [comment]
@Elovard , thanks for the review!
the three first are fixed the fourth is left for the #4 / #5 
the pr - https://github.com/daverbk/evolve/pull/3
